#Version: 0.0.1
FROM	quay.io/centos/centos:stream9
ENV	REFRESHED_AT 2023-10-28-01

RUN	dnf update -y
RUN	dnf install -y git python
RUN	mkdir /root/smallfile
RUN	git clone https://github.com/distributed-system-analysis/smallfile.git /root/smallfile
COPY	run_test.sh /root/smallfile
RUN	chmod +x /root/smallfile/run_test.sh
WORKDIR	/root/smallfile
CMD	["/root/smallfile/run_test.sh"]
